/* USER CODE BEGIN Header */
/**
 ******************************************************************************
 * @file           : main.c
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * The following copyright was generated by STM32CubeMX. Original contributions
 * from the author may be held under a different copyright. 👇
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include "alerts.h"
#include "defines.h"
#include "determination_logic.h"
#include "error_codes.h"
#include "hardware.h"
#include "interrupts.h"
#include "logging.h"
#include "math.h"
#include "rtc.h"
#include "sensor.h"
#include "stm32.h"
#include "string.h"
#include "usb_comm.h"

/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/

/* USER CODE BEGIN PV */

static Sensor sensors[SENSOR_COUNT]; // An array to hold the data associated with each sensor
float displayTemp = NAN; // A float to hold the 'display temperature' after calculated (or NAN)

// A variable to determine whether enough time has passed since the last read session
volatile uint8_t readNow = 1;

/*USART Message Handling Variables*/
uint8_t setTime = 0; // Used to tell the system that the RTC is ready to be set
volatile uint8_t usartMessage[BUFFER_SIZE]; // A buffer to hold completely received USART messages

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/

/* USER CODE BEGIN PFP */
void prepNextSensorRead(void);
void usartMessageHandler(void);
void RTC_RequestTime(void);

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

/**
 * @brief  The application entry point.
 * @retval int
 */
int main(void)
{

    /* USER CODE BEGIN 1 */

    /* USER CODE END 1 */

    /* MCU Configuration--------------------------------------------------------*/

    /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
    HAL_Init();

    /* USER CODE BEGIN Init */

    /* USER CODE END Init */

    /* Configure the system clock */
    SystemClock_Config();

    /* USER CODE BEGIN SysInit */

    /* USER CODE END SysInit */

    /* Initialize all configured peripherals */
    MX_GPIO_Init();
    MX_I2C1_Init();
    MX_USART2_UART_Init();
    MX_RTC_Init();
    MX_SPI1_Init();
    MX_TIM16_Init();
    /* USER CODE BEGIN 2 */

    /*Verify expected temp sensors are communicating, and initialize structs for the sensors*/
    setupSensors(SENSOR_COUNT, sensors);

    // Setup timer 16 interrupt for reading the temp sensor registers every
    // REQUESTED_SENSOR_SAMPLING_INTERVAL_SEC seconds...
    setTIMInterrupt();

    // Setup the USART Interrupt...
    setUSARTInterrupt();

    // Request information via USART to set RTC Clock
    RTC_RequestTime();

    /* USER CODE END 2 */

    /* Infinite loop */
    /* USER CODE BEGIN WHILE */
    while (1)
    {
        if (readNow) // If the timer 16 interrupt has fired since the last sensor reading session...
        {
            readNow = 0;
            if (!readTempSensors(sensors)) // If failure occurs with communication to all sensors...
            {
                logError(ALL_SENSOR_READS_MISSING, -1); //...log an 'ALL_SENSOR_READS_MISSING' error
            }
            displayTemp = determineTemp(sensors); // Otherwise, use those readings (and any flags
                                                  // set) to determine a 'display temperature'
            logData(displayTemp, sensors);        // Send a data log entry over USART
            setAlerts(sensors);                   // Set buzzer and LEDs as appropriate
            prepNextSensorRead(); // Prepare for the next sensor reading/polling session
        }
        usartMessageHandler();   // Handle any messages received via USART
        interruptErrorHandler(); // Log any errors that occured based on flags set during interrupt
                                 // code
        updateBuzzer(); // Turns off the buzzer if the buzzer is active and no longer supposed to be
                        // turned on
        /* USER CODE END WHILE */

        /* USER CODE BEGIN 3 */
    }
    /* USER CODE END 3 */
}

/* USER CODE BEGIN 4 */

void prepNextSensorRead(void)
{
    clearFaults(sensors);
    displayTemp = NAN;
}

void RTC_RequestTime(void)
{
    setTime = 1;
    usb_println("SEND_TIME");
}

void usartMessageHandler(void)
{
    if (fullMessageReceived) // If a full message has been received, then process the received
                             // transmission information
    {
        if (setTime == 1)
        {
            // If the program progresses here, it should have received the time data

            int8_t returnCode = RTC_SetTime(); // Attempt to set the RTC with the received data
            if (returnCode)
            {                       // If an error occurs...
                switch (returnCode) // Log the appripriate error
                {
                    case 1:
                        logError(RTC_FORMATTING_ERROR, -1); // That could be a formatting error...
                        break;
                    case 2:
                        logError(RTC_INVALID_DATETIME_ERROR, -1); //...or maybe this error
                        break;
                    case 3:
                        logError(RTC_SET_ERROR, -1); //...or maybe even this error!
                        break;
                    default:
                        logError(UNRECOGNIZED_ERROR_RECEIVED, -1);
                        break;
                }
                // If an error occured, resend the "SEND_TIME" message and keep setTime = 1
                usb_print("SEND_TIME\r\n");
                setTime = 1;
            }
            else // Otherwise reset setTime to 0
            {
                setTime = 0;
            }
        }
        else if (strcmp((const char *)usartMessage, "SET_TIME") == 0)
        { // If "SET_TIME" was received...
            // Set the boolean variable to set the time after the next full message is received...
            setTime = 1;
            //...and send a "SEND_TIME" message via USART
            usb_print("SEND_TIME\r\n");
        }
        else // If none of the above commands were received, log an error
        {
            logError(UNRECOGNIZED_COMMAND_RECEIVED, -1);
        }
        /*CAN ADD FUTURE USART COMMANDS TO BE PROCESSED TO THIS CHAINED IF-ELSE BLOCK*/

        // Since the current message should now have been fully processed, reset the
        // 'fullMessageReceived' flag to false.
        fullMessageReceived = 0;
    }
    return;
}

/* USER CODE END 4 */

/**
 * @brief  This function is executed in case of error occurrence.
 * @retval None
 */
void Error_Handler(void)
{
    /* USER CODE BEGIN Error_Handler_Debug */
    /* User can add his own implementation to report the HAL error return state */
    __disable_irq();
    while (1)
    {
    }
    /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
 * @brief  Reports the name of the source file and the source line number
 *         where the assert_param error has occurred.
 * @param  file: pointer to the source file name
 * @param  line: assert_param error line source number
 * @retval None
 */
void assert_failed(uint8_t *file, uint32_t line)
{
    /* USER CODE BEGIN 6 */
    /* User can add his own implementation to report the file name and line number,
       ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
    /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
